### ISSUE TITLE
Banned while trying to log in with this software

### ISSUE THREAD

**Issue by SeaifanAladdin** [HikariKnight/rsu-client#113]
Hello,
I have used your software to play runescape for a few years now. I don't play much, and I have a habit of leaving for a few months and coming back for a few weeks.

After a few months of hiatus, I decided to log in with this software again. To my surprise, I logged in with a 48 hour ban. This is the message that Jagex sent to me.

> Our macro detection system has been monitoring your account closely and has detected that you are using illegal 3rd party software which violates the rules of the game and breaches your terms of service with Jagex.

> Our team have reviewed the evidence and can confirm that you were using illegal botting software. Should you continue to use cheating software we will permanently ban your account with no chance of appeal.

> Jagex are able to accurately detect all illegal 3rd party software and any promises from their makers about being "totally undetectable" or "no ban guaranteed" are inaccurate. We are always 100% certain before taking permanent action on an account

> A temporary ban has been placed on your account meaning you will be unable to access the game for the next 48 hours. This is not an appealable offence and we will not review it should you contact us by email, ticket or social media.

> Please take this time to familiarise yourself with the rules as we would like to see you back in game and part of the community.

> Regards,
Jagex

I've never botted before, and it's been a few months since I've last logged in. I apologize for this speculation, but It's hard for me to not suspect rsu-client.

More information:

Distribution: Fedora 23
RSU-Client version: 4.3.5
Addons: Grand Exchange Search, Player Lookup, Runescape Wiki Search, and Fullscreen Emu

**Comment by tmondrag** [comment]
If you found this out after the first time you logged in after a few month hiatus, it is entirely possible that it wasn't because you were using software that tripped Jagex's macro detection algorithms, but that someone else was botting on your account while you weren't using it. 

Jagex is very familiar with this client and have given it an officialish blessing, so they likely have done work to prevent it from triggering false positives in their botting detection algorithms.

You might want to investigate the possibility that someone else was using your account while you were away and change your password, bank pin, and Jagex Authenticator details as soon as you can.

**Comment by SeaifanAladdin** [comment]
I am ashamed to confirm that you are right, someone else has been botting on my account. I believe the hack came from the  Cloudflare leak a few weeks ago. As I'm not an active runescape player, changing my password for this game never crossed my mind. 

I apologize for suspecting this software. Thank you for your help.

**Comment by HikariKnight** [comment]
Jagex as far as i know has an exclusion for this client however it will still detect if you were doing something you weren't supposed to do like an injection or using a 3rd party tool to macro

Because in the end it's their client that is launched, the rsu client just tried to prepare everything for it to launch the best possible way
