### ISSUE TITLE
Oldschool Shortcut

### ISSUE THREAD

**Issue by GHXST01** [HikariKnight/rsu-client#123]
Hey I'm making a live usb drive with Lubuntu for a friend of mine.
He plays oldschool only and I wish to have either an oldschool shortcut on the desktop, or auto launch oldschool when launching the rsu client.

The first time I tested the install, it gave me different shortcuts, but this time it only gave me the launcher shortcut.

Any idea what to do?

@HikariKnight

**Comment by HikariKnight** [comment]
the other shortcuts exist but they are disabled since you have wxPerl available
you should be able to find them in /opt/runescape/templates/packaging/usr/share/applications

all you have to do is copy the oldschool file from that (not move) and just add it to desktop

if you want automatic startup then you need to run

/opt/runescape/runescape --prmfile=oldschool.prm &

on startup

**Comment by GHXST01** [comment]
Thanks!

Keep up the good work.

**Comment by HikariKnight** [comment]
youre welcome :+1:
