### ISSUE TITLE
Removing language and copyrights to have more room for the actual gameplay

### ISSUE THREAD

**Issue by navennn** [HikariKnight/rsu-client#127]
Is there a way to remove the language bar and copyright at the bottom of the screen? I was playing a different client for some time and it was much more convenient to play the game and to actually see a bit more of the game.
![rsu-client](https://user-images.githubusercontent.com/26810830/30128033-7d3c9e44-9341-11e7-970c-82e7a7f43084.png)

**Comment by soaringowl2145** [comment]
@HikariKnight

**Comment by ivanpu** [comment]
I don't know whether Jagex implemented this in OSRS, but in RS3 it's removed as long as you don't use Java 8.

Also see #50 and #57.

**Comment by HikariKnight** [comment]
well some more information about it, it is not possible for us to do without breaking the TOS, if we did remove it then this would no longer be an unofficial official client.

Mod Philip did remove the bars but it broke with newer java versions and he no longer works at jagex so i cannot poke him directly about it sadly.

**Comment by navennn** [comment]
That's interesting. 
I'm not really so much into this, but what's the difference between this client and osbuddy? Osbuddy fills up all the screen. As I understand it - it should be using the same version of the client, or am I wrong?

**Comment by HikariKnight** [comment]
they do not use the official applet viewer, they use one they have made themself and are then considered 3rd party, the only reason this client got featured on the actual runescape homepage before NXT was because it was essentially just an advanced opensource start script for the official appletviewer made by jagex, making the scripts 3rd party launching a 1st party program which is the actual client, and it still is, it is no longer featured on the website as of the NXT launch as it served its purpose in that time as the "linux" client until NXT was finished, but tech support still recommends the RSU client as far as i know if anyone have any issues running NXT.

**Comment by navennn** [comment]
Thanks for the explanation. I guess there is nothing else to be done than bothering jagex then.

**Comment by HikariKnight** [comment]
the linux client used to do it, Mod Philip made the code for that in the appletviewer but java8 broke it and he is no longer with jagex so there is nobody to contact to get it fixed

also i can not start using a different applet viewer with the client as i made this project to be 100% compatible with the official, it is how it was endorsed on the download page from 2014 til the release of nxt

**Comment by navennn** [comment]
Are you saying that if there is some critical bug in the future, you will not be able to fix it either?

**Comment by HikariKnight** [comment]
exactly, RSU only takes care of pre-launch operations then hands everything over to jagexappletviewer

**Comment by shuhaowu** [comment]
This project should always use Jagex's official appletviewer. Are you saying that if we bundle in OpenJDK6 (judget from the .tar.gz file I'm getting), we can get rid of the bar without additional flags? That should be easy to fix as we can easily bundle it in.

**Comment by shuhaowu** [comment]
Here's the official license source: http://www.runescape.com/downloads/jagexlauncher-src.tar.bz2?210604

It looks like they bundled OpenJDK6 with some minor patches.

**Comment by HikariKnight** [comment]
exactly, i wouldnt like bundling openjdk6 or 7 directly with the client files but if licencing accepts it it could have a download of sorts, its because of oddities like this i made the custom java option in the settings ;)

**Comment by shuhaowu** [comment]
If it does remove it without modifications, I'll investigate down this path. OpenJDK6 is pretty old and I'll need to figure out how to get a copy of this. The easiest way might be doing it inside a LXC/LXD container or sort with an old version of Ubuntu. This will give us some added benefit of isolation as well.

Might as well reopen this issue then.

**Comment by HikariKnight** [comment]
sounds like a plan, the client is pretty self contained in general when outside of /opt or /usr
it does have some checks if its run from within those locations to make it "system wide" compatible like storing config files in ~/.local or ~/.config as the user would not have write permissions to /opt or /usr in most cases

**Comment by shuhaowu** [comment]
Just launched the client with rsu-client (maybe this should be called rsu-launcher instead...) via OpenJDK6 on ubuntu trusty. It works but the copyright bar is definitely not removed upon login. I'm still suspecting that the windows launcher is passing some options/environment/something.

**Comment by HikariKnight** [comment]
i can guarantee you it does not though, so my guess is that they have broken it since it did work on java6 and 7 last time i checked but not 8

**Comment by shuhaowu** [comment]
Did you try OpenJDK or Oracle JDK? Neither 6 or 7 removes it for me.

**Comment by shuhaowu** [comment]
Does the windows client not use the same jar file? AFAICT the launcher just launchers the java vm with the jar. Thus the functionality must be there somewhere.

I'm currently using a container and running the application via an X socket that I mounted in. This allows me to test any arbitrary setup. If you can tell me what distro/java distribution/version you're running, I can verify the behaviour reasonably quickly.

**Comment by HikariKnight** [comment]
windows uses the identical jar
bars get removed with linux and mac jar on windows

all 3 jars are identical, the choice between them is just remainder from when the mac client became available and later philip added the jar directly to the rs website for clients like mine to use instead of jumping through the hoops of extracting the jar from the other clients :P

**Comment by shuhaowu** [comment]
AHA! So here lies the problem. The jar files ARE different! I just cloned and setup a new instance of rsu-client, which gave me the following jar:

```
-rw-rw-r-- 1 btw btw 62295 May 16 15:58 jagexappletviewer.jar
```

This is the jar I extracted from the windows installer. The size is slightly different.

```
-rw-rw-r-- 1 btw btw 62048 May 16 19:25 jagexappletviewer.jar
```

Indeed, when I launch the windows installer extracted jar file, the copyright and language bar disappears after login (on OpenJDK6, need to check OpenJDK8 still).

Is it time to ask jagex to update that appletviewer and extract it from the msi again?

**Comment by shuhaowu** [comment]
I just confirmed that with the windows jar, I can even use OpenJDK8 and the copyright/language bar disappears AFTER login.

**Comment by shuhaowu** [comment]
It's interesting that the dmg installer also gives a slightly different jar file:

```
-rwx------ 1 7238820 1778592242 64137 Jul 11  2017 jagexappletviewer.jar
```

Ignore the first two numbers as I'm mounting the dmg image and the uid/gid are a bit messed up.

**Comment by HikariKnight** [comment]
so jagex has essentially no control which file is which? hmm
i might be able to contact someone at jagex to poke the devs to update the jar but no promises, test the osx one which seems to be the most up to date one (size wise) but we wont know for sure until you test :)

**Comment by shuhaowu** [comment]
Nope, the mac one doesn't remove the bar, just the windows one works.

I'm guessing that Jagex just doesn't update http://www.runescape.com/downloads/jagexappletviewer.jar when they update the appletviewer as they only focused on getting the Windows installer to work.

Also note that I'm using the OSRS installer here.

**Comment by shuhaowu** [comment]
Additionally, trying to get the appletviewer from the runescape.msi gets the same one as the default linux one: https://github.com/rsu-client/rsu-client/blob/master/runescape/rsu/framework/API/client/launch/updater.pm#L35

**Comment by HikariKnight** [comment]
so rs3 used old source to make updated appletviewers and oldschool used the newer source lol
great xD

**Comment by shuhaowu** [comment]
This seems like what's happening.. Not sure why the oldschool.dmg also has a viewer that doesn't get rid of the black bar. Chances are their build pipeline for the launcher is probably never polished unless people complain, and since Mac users who use the official client is likely tiny, they just never bothered.

I have that PR up there that gets rid of the black bars for Linux by switching the default method of downloading the jar to extracting the msi. It would be great if you can review and merge it :)

**Comment by HikariKnight** [comment]
initiate a pull request and i will be able to do it

**Comment by shuhaowu** [comment]
It's already up. See #141

**Comment by HikariKnight** [comment]
was looking at the wrong place :P

**Comment by shuhaowu** [comment]
Thanks a LOT for all the help getting to the bottom of this issue! The black bar always bothered me but it's not until today I checked the windows installer and realized that the black bar disappeared.

**Comment by shuhaowu** [comment]
Actually one more thing, we might want to have a way to update the existing appletview.jar file so people who already have this installed can get this benefit, perhaps we can check the file size, if it matches the old file size, then try to update?

**Comment by HikariKnight** [comment]
i never wrote such a function since the appletviewer would complain when it was outdated but since the current ones are outdated but not at the same time they would have to update the client anyway, plus it would cause issues in the future should they update it as we cant have the client download and check the rar for changes each time the client starts since wxperl at least when i wrote this didnt have proper support for threads so it would hang if the website has issues.

**Comment by shuhaowu** [comment]
No I'm not saying we should check for an update online. Instead, what I'm saying is: since we know the default file size of `62295` is an outdated client, if we detect that a jar exist on the user's filesystem, and it has that exact file size, we can try to download a newer client. 

Over the next little while this would bring people's jar up to date. It is a little hacky, but it otherwise I don't think the majority of people will ever see the benefits of that PR, unless we can announce the change and the procedures to update somehow..

**Comment by navennn** [comment]
Thank you guys for getting to the bottom of this.
One more question- how do I upgrade to use it? Can you upgrade the repo version please?

**Comment by shuhaowu** [comment]
That's what I was talking about. You can just upgrade your version (git pull, whatever), and then you have to delete the jagexappletviewer.jar. Alternatively I think you can also use the appletviewer updater to update it.

**Comment by navennn** [comment]
ok! not blunt enough for me :)
removed /home/username/.config/runescape/bin/jagexappletviewer.jar
ran the client and it downloaded a new one just like you said

Thanks guys! It works.

**Comment by Espionage724** [comment]
I have some notes to add to this issue:

- With `jagexappletviewer.jar` from `OldSchool.msi` (Windows), seemingly any JDK newer than 11 will prevent the copyright footer from being hidden
- With `jagexappletviewer.jar` from `OldSchool.dmg` (macOS) however, if the flag `-Djava.system.class.loader=app.systemclassloader` is being used, the copyright footer is hidden seemingly regardless of the JDK version (works fine with OpenJDK 13 on Linux)
- `-Djava.system.class.loader=app.systemclassloader` doesn't work with the Windows jar

So in-short, the best experience I've found on both macOS and Linux is to use `jagexappletviewer.jar` from `OldSchool.dmg`, and to use the `-Djava.system.class.loader=app.systemclassloader` flag.
