### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by Unk1** [HikariKnight/rsu-client#78]
Hi!

@HikariKnight

I got banned by Jagex Anti-Botting system by using this client. Perm banned.
No warning at all. Got warning 12:20 CET 2015-11-16; then 12:30 three automatic Perm banned notes.

RSN: skatedawe
I've been member for 11years and playing runescape since 2013, November.

I want to warn you about this and all the players. It's impossible to communicate with the staff. I can't find any answers regarding this. It's un-appealable. :(

Any suggestions and advice?

On the Official Runescape Wiki it states and also refers to this project.

Thankful for advices, comments etc.
If any staff from Jagex read this, please contact me; unk[at]raht.org

Best Regards,
David

![selection_071](https://cloud.githubusercontent.com/assets/15911597/11247841/27963966-8e1e-11e5-8b6d-0838e4228e1f.png)
![selection_072](https://cloud.githubusercontent.com/assets/15911597/11247842/279bed98-8e1e-11e5-8507-dea562efdeac.png)
![selection_073](https://cloud.githubusercontent.com/assets/15911597/11247843/27a08560-8e1e-11e5-8545-6fdf98076000.png)

**Comment by Unk1** [comment]
from /var/log/dpkg;

When removing the project from computer:

Start-Date: 2015-11-16  18:07:09
Commandline: apt-get remove runescape
Remove: unix-runescape-client:amd64 (3.2-2), runescape:amd64 (201509210840~git-master~ubuntu14.04.1)
End-Date: 2015-11-16  18:07:10

**Comment by HostOnNet** [comment]
I dot see why rsu-client can get you banned. Client itself is created by jagex. Client is buggy after they removed the copy right thing, every time i login, it force me mis click as mouse click few pixels off, look like they have not compensated for extra pixels freed when removing copyright or something, i think this can trigger macro system.

Just remembered, i should try updating .jar file (i don't get any rsu-client UI as i git cloned and some perl module missing, don't want that, happy with the way it works now).

**Comment by Unk1** [comment]
I don't understand it either, i would never bot/macro etc, loyal member since 2005.

**Comment by ivanpu** [comment]
This client is more appropriately should be called "launcher": all it does is optimizes java environment and launches the actual client that is written by Jagex.
It does not interact with the game in any way... unless some of the extensions does.
Have you any of the extensions installed for it, btw?

And about the offset in visuals:
It is [well known bug](http://services.runescape.com/m=rswiki/en/Linux_Known_Issues#After_changing_size_of_window_client.2C_graphics_are_messed_up) with the game on Linux in OpenGL mode.
Just minimizing/unminimizing window usually fixes it after a few times.

**Comment by Unk1** [comment]
Thanks for input. No addon what i know of, never used it if.

**Comment by HikariKnight** [comment]
From what i know, it could be from having some blacklisted software running in the background.
And i know that RSU itself is in a whitelist, i will try to poke someone that can check this further but i cannot promise any results as this is not the way to deal with bans.

**Comment by Unk1** [comment]
@HikariKnight Thanks! Do you know somehow to appeal. There is no way to reach the admins etc, what i've know. The ban is not ban is not appeal-able which reach me to a dead end, which is a public disgrace for Jagex.

**Comment by HikariKnight** [comment]
you have been unbanned and it will be looked into further, keep in mind this is not normal practice so consider yourself lucky

**Comment by bascuppen** [comment]
Hi @HikariKnight ,

I know this was unusual, and not normal practice. However, I was banned for using the RSU client in 17-Jun-2015. 

Perm banned. And likewise: No warning at all. 

RSN: Ba Si
At the time I was struggling with myself and putting crazy amounts of time into the game. The ban made me lose contact to fellow players who I had a bond with.

I do appreciate Jagex commitment to their policy of no communication on this subject. However, I tried to proof it was caused by logging in by using the RSU client I had installed. I made a new RS account, logged in with the windows client -> no problems. Booted, launched the RSU client and instanly got banned.
[https://youtu.be/XmDUBqqEL68](url)

I have been speculating about this ever since. Could it be that a build signature was changed in the repositories?

If you still are in a position to 'nudge' someone.. I know it is a huge favour to ask..

Best Regards,

Ba Si

**Comment by HikariKnight** [comment]
hey @bascuppen i managed to get hold of someone to show your video, it is a very old video but they will take a look through the data they have and check over the account and to see if the account is eligible to any changes.

however they requested me to tell you to submit another ban appeal so that they can start the process of reviewing everything (strict routines and all that).

Feel free to refer to this github ticket for reference if you want to.
i would recommend using the permalink to your message so they see the right message
https://github.com/rsu-client/rsu-client/issues/78#issuecomment-541294693

Have a nice day and good luck!
