### ISSUE TITLE
SDL Framebuffer Output

### ISSUE THREAD

**Issue by CaptainMcClellan** [HikariKnight/rsu-client#86]
Request: Outputting the display to a framebuffer driver/interface of some sort for Linux systems not running with a windowing environment.

**Comment by ivanpu** [comment]
Are you asking for this launcher, or for the game itself?

### rsu-client

I think it may be possible, but most work should be done on your side:

1. You have to [compile wxDFB](https://github.com/wxWidgets/wxWidgets/blob/master/docs/dfb/install.txt).
2. You may need to recompile/reconfigure wxPerl to use wxDFB instead of wxGTK.

Then the client should run in framebuffer, except all the unimplemented stuff in wxDFB.

### The game itself

More research needed, but if there is no "magic" command line parameter for Java, this is out of our scope. Most likely this kind of support is only doable in the code itself, and hence can only be done by Jagex.

**Comment by HikariKnight** [comment]
closed due to inactivity
